namespace Condition_Criteria_App
{
    public static class ANotesData
    {
        public static readonly List<ANotesEntry> Entries = new List<ANotesEntry>
    {
        new() {DC = "5240-A", AreaNote = "Favorable ankylosis means that the joint is stiff or fused, but is in a neutral or upright position.Unfavorable ankylosis means the joint is permanently ridigd in an abnormal or uncomfortable position."},
        new() {DC = "5243", AreaNote = "IVDS criteria requires bed rest that is prescribed by a physician, proof of this prescription must be provided if increasing by IVDS criteria. Otherwise, increase IVDS by limited ROM. Of note, if Veteran is increased to 60 on IVDS, radiculopathy CANNOT be added as secondary."},
        new() {DC = "5240-B", AreaNote = "Favorable ankylosis means that the joint is stiff or fused, but is in a neutral or upright position.Unfavorable ankylosis means the neck is permanently ridigd in an abnormal or uncomfortable position."},
        new() {DC = "5205-1", AreaNote = "Favorable ankylosis means that the joint is stiff or fused, but is in a neutral position.Unfavorable ankylosis means the joint is permanently ridigd in an abnormal or uncomfortable position."},
        new() {DC = "5205-2", AreaNote = "Favorable ankylosis means that the joint is stiff or fused, but is in a neutral position.Unfavorable ankylosis means the joint is permanently ridigd in an abnormal or uncomfortable position."},
        new() {DC = "5214-1", AreaNote = "Extremely unfavorable ankylosis will be rated as loss of use of hands"},
        new() {DC = "5214-2", AreaNote = "Extremely unfavorable ankylosis will be rated as loss of use of hands"},
        new() {DC = "5256", AreaNote = "Knees can have up to three ratings for limitation of motion (flexion, extension, and/or instability)"},
        new() {DC = "5257", AreaNote = "For higher instability ratings must have documentation of a prescribed knee brace for instability treatment, as well as surgery."},
        new() {DC = "5262", AreaNote = "Cannot be increased based on limited range of motion.If attempting for shin splints and knee condition; they will be combined as one rating and the highest rating of conditions will be awarded."},
        new() {DC = "5251", AreaNote = "Hips can have up to three ratings for limitation of motion (flexion, extension, and one of the thigh impairments)"},
        new() {DC = "5297", AreaNote = "The rating for rib resection or removal cannot be applied with ratings for purrulent pleurisy, lobectomy, pneumonectomy or injuries of pleural cavity.However, rib resection will be considered as rib removal in thoracoplasty performed for collapse therapy or to accomplish obliteration of space and will be combined with the rating for lung collapse, or with the rating for lobectomy, pneumonectomy or the graduated ratings for pulmonary tuberculosis."},
        new() {DC = "5296", AreaNote = "Rate separately for intracranial complications."},
        new() {DC = "5275", AreaNote = "Measure the leg length from the front hip bone to the inner ankle, and don’t combine this measurement with other ratings for fractures or bone healing problems in the same leg."},
        new() {DC = "7202", AreaNote = "Speech problems should be rated as complete loss of voice (aphonia) DC 6519 or, if partial loss of voice DC 6516, as chronic laryngitis.*Dietary modifications due to this condition must be prescribed by a medical provider."},
        new() {DC = "7203-7207", AreaNote = "Documeted history means that the Veteran has medical records that confirm a diagnosis of 'esophageal stricture', without this, increase cannout occur. Findings must be documented by barium swallow, CT, or EGD."},
        new() {DC = "7204", AreaNote = "Documeted history means that the Veteran has medical records that confirm a diagnosis of 'esophageal stricture', without this, increase cannout occur. Findings must be documented by barium swallow, CT, or EGD."},
        new() {DC = "7205", AreaNote = "Documeted history means that the Veteran has medical records that confirm a diagnosis of 'esophageal stricture', without this, increase cannout occur. Findings must be documented by barium swallow, CT, or EGD."},
        new() {DC = "7206", AreaNote = "Documeted history means that the Veteran has medical records that confirm a diagnosis of 'esophageal stricture', without this, increase cannout occur. Findings must be documented by barium swallow, CT, or EGD."},
        new() {DC = "7207", AreaNote = "If Veteran has confirmed diagnoses of esophageal stricutre, this condition can be rated under esophageal stricutre criteria. Findings must be documented by barium swallow, CT, or EGD."},
        new() {DC = "7308", AreaNote = "Rate residuals as chronic complications of upper gastrointestinal surgery (DC 7303)."},
        new() {DC = "7309-A", AreaNote = "Chronic Complications of Upper Gastrointestinal Surgery DC 7303"},
        new() {DC = "7309-B", AreaNote = "Peptic Ulcer Disease DC 7304"},
        new() {DC = "7323", AreaNote = "Rate as Crohn's disease or undifferentiated form of inflammatory bowel disease (DC 7326)."},
        new() {DC = "7332", AreaNote = "Complete or partial loss of sphincter control refers to the inability to retain or expel stool at an appropriate time and place."},
        new() {DC = "7334", AreaNote = "For repairable prolapse of the rectum, continue the 100% evaluation for two months following repair. Then Veteran will need to attend a mandatory VA exam to determine how the condition will be rated."},
        new() {DC = "7351", AreaNote = "Assign a rating of 100% as of the date of hospital admission for transplant surgery. One year following discharge, Veteran must attend a mandatory VA exam to determine how residuals of condition will be rated."},
        new() {DC = "7352", AreaNote = "Assign a rating of 100% as of the date of hospital admission for transplant surgery. One year following discharge, Veteran must attend a mandatory VA exam to determine how to rate residual symptoms."},
        new() {DC = "7355", AreaNote = "An appropriate serum antibody test or endoscopy with biopsy must confirm the malabsorption diagnosis."},
        new() {DC = "7357", AreaNote = "Minimum evaluation of 30, othewise will be rated based on complictions from any of the following (Chronic pancreatitis, chronic complications of upper gastrointestinal surgery, intestinal resection, irritable bowel syndrome, Crohn's disease, diabetes)."},
        new() {DC = "7804", AreaNote = "* An unstable scar is one where, for any reason, there is frequent loss of covering of skin over the scar."},
        new() {DC = "7806", AreaNote = "Systemic therapy is treatment that is adminsitered through any route OTHER than skin (topical)."},
        new() {DC = "7807-C", AreaNote = "Systemic therapy is treatment that is adminsitered through any route OTHER than skin (topical)."},
        new() {DC = "7808-C", AreaNote = "Systemic therapy is treatment that is adminsitered through any route OTHER than skin (topical)."},
        new() {DC = "7809", AreaNote = "Systemic therapy is treatment that is adminsitered through any route OTHER than skin (topical)."},
        new() {DC = "7813", AreaNote = "Systemic therapy is treatment that is adminsitered through any route OTHER than skin (topical)."},
        new() {DC = "7815", AreaNote = "Systemic therapy is treatment that is adminsitered through any route OTHER than skin (topical)."},
        new() {DC = "7816", AreaNote = "Systemic therapy is treatment that is adminsitered through any route OTHER than skin (topical)."},
        new() {DC = "7817", AreaNote = "Systemic therapy is treatment that is adminsitered through any route OTHER than skin (topical)."},
        new() {DC = "7819-A", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria."},
        new() {DC = "7819-B", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria."},
        new() {DC = "7818-A", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria."},
        new() {DC = "7818-B", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria."},
        new() {DC = "7825", AreaNote = "Chronic urticaria means hives that occur at least twice a week without treatment and last for six weeks or more"},
        new() {DC = "7826", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria."},
        new() {DC = "7827", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria.* For the purposes of this DC only, systemic therapy may consist of one or more of the following treatment agents: immunosuppressives, antihistamines, or sympathomimetics."},
        new() {DC = "7828-B", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria."},
        new() {DC = "7828-C", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria."},
        new() {DC = "7829", AreaNote = "If condition has resulted in disfigurement of the head, face, or neck, painful or unstable scars, or hause caused impairment in Veteran's functioning. Rate under applicable criteria."},
        new() {DC = "7901", AreaNote = "Evaluate symptoms of hyperthyroidism under DC 7900, hyperthyroidism, including, but not limited to, Graves' disease."},
        new() {DC = "7907", AreaNote = "The evaluations specifically indicated under this diagnostic code shall continue for six months following initial diagnosis. After six months, rate on residuals under the appropriate diagnostic code(s) within the appropriate body system(s)."},
        new() {DC = "7911", AreaNote = "Addisonian crisis → “A sudden, life-threatening event with very low blood pressure and shock, which may include loss of appetite, nausea, vomiting, dehydration, extreme weakness, pain, fever, mental changes, coma, kidney failure, and possibly death.”Addisonian episode → “A milder event than a crisis, with symptoms like loss of appetite, nausea, vomiting, diarrhea, dehydration, weakness, feeling unwell, dizziness on standing, or low blood sugar, but without collapse or shock.”Tuberculous Addison’s disease → “If caused by tuberculosis, it is rated as active or inactive TB, and the rating is not added to the standard non-pulmonary TB ratings—only the higher rating is given.”"},
        new() {DC = "7913", AreaNote = "* Evaluate compensable complications of diabetes separately unless they are part of the criteria used to support a 100-percent evaluation. Noncompensable complications are considered part of the diabetic process under DC 7913.*  When diabetes mellitus has been conclusively diagnosed, do not request a glucose tolerance test solely for rating purposes."},
        new() {DC = "8017", AreaNote = "Consider the need for special monthly compensation."},
        new() {DC = "8103", AreaNote = "Depending upon frequency, severity, muscle groups involved."},
        new() {DC = "8108", AreaNote = "Rate as for epilepsy, petit mal."},
        new() {DC = "8205", AreaNote = "Dependent upon relative degree of sensory manifestation or motor loss."},
        new() {DC = "8207", AreaNote = "Dependent upon relative loss of innervation of facial muscles."},
        new() {DC = "8209", AreaNote = "Dependent upon relative loss of ordinary sensation in mucous membrane of the pharynx, fauces, and tonsils."},
        new() {DC = "8210", AreaNote = "Dependent upon relative loss of ordinary sensation in mucous membrane of the pharynx, fauces, and tonsils."},
        new() {DC = "8211", AreaNote = "Dependent upon loss of motor function of sternomastoid and trapezius muscles."},
        new() {DC = "8212", AreaNote = "Dependent upon loss of motor function of tongue."},
        new() {DC = "8514-1", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8514-2", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8515-1", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8515-2", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8516-1", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8516-2", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8517-1", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8517-2", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8518-1", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8518-2", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8519-1", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8519-2", AreaNote = "Requires nerve testing to support severity"},
        new() {DC = "8911", AreaNote = "* When continuous medication is shown necessary for the control of epilepsy, the minimum evaluation will be 10 percent. This rating will not be combined with any other rating for epilepsy.* In the presence of major and minor seizures, rate the predominating type.* There will be no distinction between diurnal and nocturnal major seizures."},
        new() {DC = "10000", AreaNote = "The DC code is NOT an actual code, this falls under multiple DC codes."},
        new() {DC = "7000", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7001-7002", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7003", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7004", AreaNote = "Evaluate syphilitic aortic aneurysms under DC 7110 (Aortic aneurysm: Ascending, thoracic, abdominal)."},
        new() {DC = "7005", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7006", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7007", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7008", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7009", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7010", AreaNote = "Examples of supraventricular tachycardia → Types include atrial fibrillation, atrial flutter, sinus tachycardia, and other fast heart rhythms starting above the ventricles.Treatment intervention → This means a patient with symptoms needs IV medicine, an electrical shock to reset the heart (cardioversion), or a procedure to remove the abnormal rhythm source (ablation)."},
        new() {DC = "7011", AreaNote = "If a patient is hospitalized for a sustained ventricular arrhythmia or surgery to remove a ventricular aneurysm, a 100% rating starts from admission and continues until 6 months after discharge, when a VA exam decides the new rating based on lasting effects"},
        new() {DC = "7015-A", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7015-B", AreaNote = "Non-Benign (Second-Degree, Type II and Third-Degree): Evaluate under DC 7018 (implantable cardiac pacemakers)."},
        new() {DC = "7016", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7017", AreaNote = "Heart failure symptoms include, but are not limited to, breathlessness, fatigue, chest pain, dizziness, arrhythmia, palpitations, or fainting."},
        new() {DC = "7101", AreaNote = "High blood pressure must be confirmed by readings on at least three different days; hypertension means the lower number (diastolic) is usually 90 or higher, and isolated systolic hypertension means the top number is usually 160 or higher while the bottom number stays under 90.**If Veteran is utilizing medications that keep their blood pressure values under the BP values specified, they will not qualify for increase due to the medciation controlling their blood pressure.**"},
        new() {DC = "7111", AreaNote = "Following surgery: Evaluate under DC 7114 (peripheral arterial disease)."},
        new() {DC = "7112", AreaNote = "If symptomatic, evaluate according to body system affected. Following surgery, evaluate residuals under the body system affected."},
        new() {DC = "7114", AreaNote = "Must obtain an Ankle-Brachial Index (ABI)."},
        new() {DC = "7117", AreaNote = "For Raynaud’s syndrome, attacks mean the fingers or toes change color for minutes to hours, sometimes with pain or tingling, triggered by cold or stress; the rating covers the condition as a whole, no matter how many body parts are affected."},
        new() {DC = "6504", AreaNote = "Or evaluate as DC 7800, scars, disfiguring, head, face, or neck."},
        new() {DC = "6510-6514", AreaNote = "An incapacitating episode of sinusitis means one that requires bed rest and treatment by a physician."},
        new() {DC = "6520", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year. Or evaluate as aphonia (DC 6519)."},
        new() {DC = "6600", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6601", AreaNote = "An incapacitating episode is one that requires bedrest and treatment by a physician."},
        new() {DC = "6602", AreaNote = "If rating the condition under test results, then a Pulmonary Function Test (PFT) is needed within the last year.  Otherwise can be increased based on medication use."},
        new() {DC = "6603", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6604", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6817", AreaNote = "Evaluate other residuals following pulmonary embolism under the most appropriate diagnostic code, such as chronic bronchitis (DC 6600) or chronic pleural effusion or fibrosis (DC 6844), but do not combine that evaluation with any of the above evaluations."},
        new() {DC = "6825", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6826", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6827", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6828", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6829", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6830", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6831", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6832", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6833", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6840", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6841", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6842", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6843", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6844", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6845", AreaNote = "Requiers Pulmonary Function Test (PFT) within the last year."},
        new() {DC = "6846", AreaNote = "Or rate active disease or residuals as chronic bronchitis (DC 6600) and extra-pulmonary involvement under specific body system involved"},
        new() {DC = "6300", AreaNote = "Rate residuals of cholera and non-cholera vibrio infections, such as renal failure, skin, and musculoskeletal conditions, within the appropriate body system."},
        new() {DC = "6301", AreaNote = "Active disease treatment → A 100% rating continues during treatment and for 6 months after it ends; then a VA exam decides the new rating, and any lasting problems (like liver or bone marrow damage) are rated under the affected body system.Recurrence of infection → If the infection comes back, it must be confirmed by lab tests such as culture or tissue studies. Confirm the recurrence of active infection by culture, histopathology, or other diagnostic laboratory testing."},
        new() {DC = "6302", AreaNote = "A 100% rating continues during treatment and for 6 months after it ends; then a VA exam sets the new rating, and any lasting problems like skin lesions, nerve damage, or amputations are rated under the affected body system"},
        new() {DC = "6304", AreaNote = "Malaria is diagnosed at first or during relapse by finding the parasite in blood tests or with specific lab tests like antigen, antibody, or PCR tests. Any lasting problems from malaria, such as liver damage, spleen damage, or nervous system issues, are rated under the affected body system. Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, liver or splenic damage, and central nervous system conditions."},
        new() {DC = "6305", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, epididymitis, lymphangitis, lymphatic obstruction, or lymphedema affecting extremities, genitals, and/or breasts."},
        new() {DC = "6306", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, endocarditis or skin lesions."},
        new() {DC = "6307", AreaNote = "Rate under the appropriate body system any residual disability of infection."},
        new() {DC = "6308", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, heart damage."},
        new() {DC = "6310", AreaNote = "Will be rated based on residuals and the affected area."},
        new() {DC = "6314", AreaNote = "Thereafter rate residuals under the appropriate body system."},
        new() {DC = "6316", AreaNote = "* Culture, serologic testing, or both must confirm the initial diagnosis and recurrence of active infection.* Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, meningitis, liver, spleen and musculoskeletal conditions."},
        new() {DC = "6317", AreaNote = "* Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, bone marrow, spleen, central nervous system, and skin conditions.* This diagnostic code includes, but is not limited to, scrub typhus, Rickettsial pox, African tick-borne fever, Rocky Mountain spotted fever, ehrlichiosis, or anaplasmosis."},
        new() {DC = "6318", AreaNote = "* Confirm by culture or other specific diagnostic laboratory tests the initial diagnosis and any relapse or chronic activity of infection.* Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, arthritis, lung lesions, or meningitis."},
        new() {DC = "6319", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, arthritis, Bell's palsy, radiculopathy, ocular, or cognitive dysfunction."},
        new() {DC = "6320", AreaNote = "Rate under the appropriate body system any residual disability of infection."},
        new() {DC = "6325", AreaNote = "Continue the rating of 100 percent through active disease followed by a mandatory VA exam. If there is no relapse, rate on residual disability. Any change in evaluation based upon that or any subsequent examination shall be subject to the provisions of § 3.105(e) of this chapter."},
        new() {DC = "6326", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, conditions of the liver, intestinal system, female genital tract, genitourinary tract, or central nervous system."},
        new() {DC = "6329", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, conditions of the central nervous system, liver, or kidney."},
        new() {DC = "6330", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, Guillain-Barre syndrome, reactive arthritis, or uveitis."},
        new() {DC = "6331", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, chronic hepatitis, endocarditis, osteomyelitis, post Q-fever chronic fatigue syndrome, or vascular infections."},
        new() {DC = "6333", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, reactive arthritis."},
        new() {DC = "6334", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, hemolytic-uremic syndrome or reactive arthritis."},
        new() {DC = "6335", AreaNote = "Rate under the appropriate body system any residual disability of infection, which includes, but is not limited to, variable physical, functional, or cognitive disabilities."},
        new() {DC = "6350", AreaNote = "Evaluate this condition either by combining the evaluations for residuals under the appropriate system, or by evaluating DC 6350, whichever method results in a higher evaluation."},
        new() {DC = "6354", AreaNote = "For the purpose of evaluating this disability, incapacitation exists only when a licensed physician prescribes bed rest and treatment."}
    };
    }
}
