namespace Condition_Criteria_App
{
    public static class AreaData
    {
        public static readonly List<AreaEntry> Entries = new List<AreaEntry>
        {
            new() { Area = "Ankle", Name = "Limited Motion", DC = "5271", R1 = 10, R2 = 20, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Ankle", Name = "Ankylosis", DC = "5270", R1 = 20, R2 = 30, R3 = 40, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Ankle", Name = "Os calcis or astragalus", DC = "5273", R1 = 10, R2 = 20, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Ankle", Name = "Astragalectomy", DC = "5274", R1 = 20, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Ankle", Name = "Replacement", DC = "5056", R1 = 20, R2 = 40, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Thoracolumbar Spine (Limited Motion)", DC = "5235-5243-A", R1 = 10, R2 = 20, R3 = 40, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Thoracolumbar Spine (Ankylosis)", DC = "5240-A", R1 = 40, R2 = 50, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Intervertebral Disc Syndrome", DC = "5243", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Sciatic Nerve)", DC = "8520", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (External Popliteal/Common Peroneal)", DC = "8521", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Musculocutaneous/Superficial Peroneal)", DC = "8522", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Anterior Tibial Nerve/Deep Peroneal)", DC = "8523", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Internal Popliteal/Tibial)", DC = "8524", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Posterior Tibial Nerve)", DC = "8525", R1 = 10, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Anterior Crural Nerve/Femoral)", DC = "8526", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Internal Saphenous Nerve)", DC = "8527", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Obturator Nerve)", DC = "8528", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (External Cutaneous Nerve of Thigh)", DC = "8529", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Back", Name = "Radiculopathy Secondary (Ilio-Inguinal Nerve)", DC = "8530", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Cervical Spine (Limited Motion)", DC = "5235-5243-B", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Cervical Spine (Ankylosis)", DC = "5240-B", R1 = 30, R2 = 40, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Radiculopathy Secondary (Upper Radicular Group) Dominant Arm", DC = "8510-1", R1 = 20, R2 = 40, R3 = 50, R4 = 70, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Radiculopathy Secondary (Upper Radicular Group) Non-dominant Arm", DC = "8510-2", R1 = 20, R2 = 30, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Radiculopathy Secondary (Middle Radicular Group) Dominant Arm", DC = "8511-1", R1 = 20, R2 = 40, R3 = 50, R4 = 70, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Radiculopathy Secondary (Middle Radicular Group) Non-dominant Arm", DC = "8511-2", R1 = 20, R2 = 30, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Radiculopathy Secondary (Lower Radicular Group) Dominant Arm", DC = "8512-1", R1 = 20, R2 = 40, R3 = 50, R4 = 70, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Radiculopathy Secondary (Lower Radicular Group) Non-dominant Arm", DC = "8512-2", R1 = 20, R2 = 30, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Radiculopathy Secondary (All Radicular Group) Dominant Arm", DC = "8513-1", R1 = 20, R2 = 40, R3 = 70, R4 = 90, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neck", Name = "Radiculopathy Secondary (All Radicular Group) Non-dominant Arm", DC = "8513-2", R1 = 20, R2 = 30, R3 = 60, R4 = 80, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Dominant (Flexion Limitation)", DC = "5206-1", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = 40, R6 = 50, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Non-Dominant (Flexion Limitation)", DC = "5206-2", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = 40, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Dominant Arm (Extension Limitation)", DC = "5207-1", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = 50, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Non-Dominant Arm (Extension Limitation)", DC = "5207-2", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Dominant Arm (Limitation of Pronation)", DC = "5213-A-1", R1 = 20, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Non-Dominant Arm (Limitation of Pronation)", DC = "5213-A-2", R1 = 20, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Dominant Arm (Limitation of Supination)", DC = "5213-B-1", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Non-Dominant Arm (Limitation of Supination)", DC = "5213-B-2", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Ankylosis Dominant Arm", DC = "5205-1", R1 = 40, R2 = 50, R3 = 60, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Ankylosis Non-Dominant Arm", DC = "5205-2", R1 = 30, R2 = 40, R3 = 50, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Flail Joint Dominant & Non-Dominant Arm", DC = "5209-2", R1 = 20, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Ulna Impairment Dominant Arm", DC = "5211-1", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Ulna Impairment Non-Dominant Arm", DC = "5211-2", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Radius Impairment Dominant Arm", DC = "5212-1", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Radius Impairment Non-Dominant Arm", DC = "5212-2", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Bone Fusion Dominant Arm", DC = "5213-C-1", R1 = 20, R2 = 30, R3 = 40, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Bone Fusion Non-Dominant Arm", DC = "5213-C-2", R1 = 20, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Replacement (Dominant Arm)", DC = "5052-1", R1 = 30, R2 = 50, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Elbow & Forearm", Name = "Replacement (Non-Dominant Arm)", DC = "5052-2", R1 = 20, R2 = 40, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Wrist", Name = "Ankylosis Dominant Arm", DC = "5214-1", R1 = 30, R2 = 40, R3 = 50, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Wrist", Name = "Ankylosis Non-Dominant Arm", DC = "5214-2", R1 = 20, R2 = 30, R3 = 40, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Wrist", Name = "Limitation of Motion Dominant Arm", DC = "5215-1", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Wrist", Name = "Limitation of Motion Non-Dominant Arm", DC = "5215-2", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Wrist", Name = "Replacement (Dominant Arm)", DC = "5053-1", R1 = 20, R2 = 40, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Wrist", Name = "Replacement (Non-Dominant Arm)", DC = "5053-2", R1 = 20, R2 = 30, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Ankylosis Dominant Arm", DC = "5200-1", R1 = 30, R2 = 40, R3 = 50, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Ankylosis Non-Dominant Arm", DC = "5200-2", R1 = 20, R2 = 30, R3 = 40, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Limitation of Motion Dominant Arm", DC = "5201-1", R1 = 20, R2 = 30, R3 = 40, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Limitation of Motion Non-Dominant Arm", DC = "5201-2", R1 = 20, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Impairment of Humerus Dominant Arm", DC = "5202-1", R1 = 20, R2 = 30, R3 = 50, R4 = 60, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Impairment of Humerus Non-Dominant Arm", DC = "5202-2", R1 = 20, R2 = 40, R3 = 50, R4 = 70, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Impairment of Clavicle Dominant Arm", DC = "5203-1", R1 = 10, R2 = 20, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Impairment of Clavicle Non-Dominant Arm", DC = "5203-2", R1 = 10, R2 = 20, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Replacement - Dominant Arm", DC = "5051-1", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shoulder and Arm", Name = "Replacement - Non-Dominant Arm", DC = "5051-2", R1 = 20, R2 = 50, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Knee and Leg", Name = "Ankylosis", DC = "5256", R1 = 30, R2 = 40, R3 = 50, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Knee and Leg", Name = "Patellar or Recurrent Instability; Subluxation", DC = "5257", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Knee and Leg", Name = "Semilunar Cartilage", DC = "5258-5259", R1 = 10, R2 = 20, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Knee and Leg", Name = "Limitation of Motion (Flexion)", DC = "5260", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Knee and Leg", Name = "Limitation of Motion (Extension)", DC = "5261", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = 40, R6 = 50, R7 = null, R8 = null },
            new() { Area = "Knee and Leg", Name = "Shin Splints", DC = "5262", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Knee and Leg", Name = "Replacement", DC = "5055", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Plantar Fasciitis - Single Foot", DC = "5269-1", R1 = 10, R2 = 20, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Plantar Fasciitis - Both Feet", DC = "5269-2", R1 = 10, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Flatfoot - One Foot", DC = "5276", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Flatfoot - Both Feet", DC = "5276-2", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Weakfoot - Both Feet", DC = "5277-2", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Claw foot (Pes Cavus) - Single Foot", DC = "5278-1", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Claw foot (Pes Cavus) - Both Feet", DC = "5278-2", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Metatarsalgia", DC = "5279", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Hallux Valgus", DC = "5280", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Hammer Toe", DC = "5282", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Tarsal/Metatarsal Bones Malunion or Nonunion", DC = "5283", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Foot", Name = "Other Foot Injury", DC = "5284", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Replacement", DC = "5054", R1 = 30, R2 = 50, R3 = 70, R4 = 90, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Ankylosis", DC = "5250", R1 = 60, R2 = 70, R3 = 90, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Limitation of Extension", DC = "5251", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Limitation of Flexion", DC = "5252", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Thight impairment (Abduction)", DC = "5253-A", R1 = 20, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Thight impairment (Adduction)", DC = "5253-B", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Thight impairment (Rotation)", DC = "5253-C", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Flail Joint", DC = "5254", R1 = 80, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Hip and Thigh", Name = "Femur Impairment", DC = "5255", R1 = 60, R2 = 60, R3 = 80, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Ribs", Name = "Rib removal", DC = "5297", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = 50, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Coccyx", Name = "Coccyx removal", DC = "5298", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "The Skull", Name = "Loss of part of the skull", DC = "5296", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Shortening of the Lower Extremity", Name = "Bone shortening of the lower extremity", DC = "5275", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = 50, R6 = 60, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Loss of Tongue", DC = "7202", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Esophageal Stricture", DC = "7203-7207", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Esophageal Motility Disorder", DC = "7204", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Esohpageal Diverticulum", DC = "7205", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Gastroesophageal Reflux Disease (GERD)", DC = "7206", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Barrett's Esophagus", DC = "7207", R1 = 10, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Peritoneal Adhesions", DC = "7301", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Chronic Complications of Upper Gastrointestinal Surgery", DC = "7303", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Peptic Ulcer Disease", DC = "7304", R1 = 0, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Chronic Gastritis", DC = "7307", R1 = 0, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Postgastrectomy Syndrome", DC = "7308", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Stomach Stenosis (chronic complications of upper gastrointestinal surgery)", DC = "7309-A", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Stomach Stenosis (peptic ulcer disease)", DC = "7309-B", R1 = 0, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Liver Cirrhosis", DC = "7312", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Chronic Biliary Tract Disease", DC = "7314", R1 = 0, R2 = 10, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Chronic Cholelithiasis", DC = "7315", R1 = 0, R2 = 10, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Gallbladder Injury (adhesions of the peritoneum 7301)", DC = "7317-A", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Gallbladder Injury (chronic gallbladder and biliary tract disease 7314)", DC = "7317-B", R1 = 0, R2 = 10, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Gallbladder Injury (cholecystectomy 7318)", DC = "7317-C", R1 = 0, R2 = 10, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Cholecystectomy", DC = "7318", R1 = 0, R2 = 10, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Irritable Bowel Syndrome", DC = "7319", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Ulcerative Colitis", DC = "7323", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Chronic Enteritis (Irritable Bowel Syndrome 7319)", DC = "7325-A", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Chronic Enteritis (Crohn's disease or inflammatory bowel disease 7326)", DC = "7325-B", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Crohn's Disease or Undifferentiated Form of Inflammatory Bowel Disease", DC = "7326", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Diverticulitis and Diverticulosis", DC = "7327", R1 = 0, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Small Intestine Resection", DC = "7328", R1 = 0, R2 = 20, R3 = 40, R4 = 60, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Large Intesting Resection", DC = "7329", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Intestinal Fistulous Disease", DC = "7330", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Peritonitis Tuberculosis", DC = "7331", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Impairment of Sphincter Control", DC = "7332", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Stricture of Rectum and Anus", DC = "7333", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Rectal Prolapse", DC = "7334", R1 = 10, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Anal Fistula and Anorectal Abscess", DC = "7335", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Hemorrhoids", DC = "7336", R1 = 10, R2 = 20, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Pruritus Ani", DC = "7337", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Hernia (Femoral, Inguinal, Umbilical, Ventral, Incisional)", DC = "7338", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = 60, R6 = 100, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Visceroptosis", DC = "7342", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Chronic Liver Disease without Cirrhosis", DC = "7345", R1 = 0, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Hital Hernia and Paraesophageal Hernia", DC = "7346", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 80, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Chronic Pancreatitis", DC = "7347", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Vagotomy with Pyloroplasty or Gastroenterostomy", DC = "7348", R1 = 20, R2 = 30, R3 = 40, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Liver Transplant", DC = "7351", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Pancreas Transplant", DC = "7352", R1 = 30, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Hepatitis C", DC = "7354", R1 = 0, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Celiac Disease", DC = "7355", R1 = 30, R2 = 50, R3 = 80, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Gastrointestinal Dysmotility Syndrome", DC = "7356", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Digestive System", Name = "Post Pancreatectomy Syndrome", DC = "7357", R1 = 30, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Burns or Scars of Body (Not Head, Face, or Neck)", DC = "7801", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Painful or Unstable Scars of the Body (Not Head, Face, or Neck)", DC = "7804", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Dermatitis or Eczema", DC = "7806", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "American Leishmaniasis (disfigurement of the head, face, or neck 7800)", DC = "7807-A", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "American Leishmaniasis (scars 7801-7805)", DC = "7807-B", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "American Leishmaniasis (dermatitis 7806)", DC = "7807-C", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Old Word Leishmaniasis (disfigurement of the head, face, or neck 7800)", DC = "7808-A", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Old Word Leishmaniasis (scars 7801-7805)", DC = "7808-B", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Old Word Leishmaniasis (dermatitis 7806)", DC = "7808-C", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Discoid Lupus Erythematosis", DC = "7809", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Dermatophytosis", DC = "7813", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Bullous Disorders", DC = "7815", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Psoriasis", DC = "7816", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Erythroderma", DC = "7817", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Noncancerous Tumor of the Skin (disfigurement of the head, face, or neck 7800)", DC = "7819-A", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Noncancerous Tumor of the Skin (scars 7801-7805)", DC = "7819-B", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Cancerous Tumor of the Skin (disfigurement of the head, face, or neck 7800)", DC = "7818-A", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Cancerous Tumor of the Skin (scars 7801-7805)", DC = "7818-B", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Other Infections of the Skin", DC = "7820", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Cutaneous Manifestations of Collagen-Vascular Diseases", DC = "7821", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Papulosquamous Disorder", DC = "7822", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Vitiligo", DC = "7823", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Keratinization Diseases", DC = "7824", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Chronic Urticaria", DC = "7825", R1 = 10, R2 = 30, R3 = 60, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Vasculitis", DC = "7826", R1 = 10, R2 = 30, R3 = 60, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Erythema Multiforme or Toxic Epidermal Necrolysis", DC = "7827", R1 = 10, R2 = 30, R3 = 60, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Acne", DC = "7828-A", R1 = 0, R2 = 10, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Superficial Acne (disfigurement of the head, face, or neck 7800)", DC = "7828-B", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Superficial Acne (scars 7801-7805)", DC = "7828-C", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Chloracne", DC = "7829", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Scarring Alopecia", DC = "7830", R1 = 0, R2 = 10, R3 = 20, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Alopecia Areata", DC = "7831", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Hyperhidrosis", DC = "7832", R1 = 0, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Malignant Melanoma (disfigurement of the head, face, or neck 7800)", DC = "7833-A", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Disease of the Skin", Name = "Malignant Melanoma (scars 7801-7805)", DC = "7833-B", R1 = 10, R2 = 20, R3 = 30, R4 = 40, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Hyperthyroidism", DC = "7900", R1 = 30, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Thyroid Enlargement", DC = "7901", R1 = 30, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Hypothyroidism", DC = "7903", R1 = 30, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Hyperparathyroidism", DC = "7904", R1 = 0, R2 = 10, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Hypoparathyroidism", DC = "7905", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Cushing's Syndrome", DC = "7907", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Acromegaly", DC = "7908", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Diabetes Insipidus", DC = "7909", R1 = 10, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Addison's Disease", DC = "7911", R1 = 20, R2 = 40, R3 = 60, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Polyglandular Syndrome", DC = "7912", R1 = 0, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Diabetes Mellitus", DC = "7913", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Cancerous tumor of the Endocrine System", DC = "7914", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Endocrine System", Name = "Noncancerous Tumor of the Endocrine System", DC = "7915", R1 = 0, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Encephalitis", DC = "8000", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Cancer of Neurololgical System", DC = "8002", R1 = 30, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Benign Cancer of Neurological System", DC = "8003", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Paralysis Agitans", DC = "8004", R1 = 30, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Bulbar Palsy", DC = "8005", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Brain Embolism", DC = "8007", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Brain Thrombosis", DC = "8008", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Brain Hemorrage", DC = "8009", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Myelitis", DC = "8010", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Poliomyelitis", DC = "8011", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Hematomyelia", DC = "8012", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Amyotrophic Lateral Sclerosis", DC = "8017", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Multiple Sclerosis", DC = "8018", R1 = 30, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Meningitis", DC = "8019", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Brain Abscess", DC = "8020", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Brain Cancer", DC = "8021", R1 = 30, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Benign Brain Cancer", DC = "8022", R1 = 10, R2 = 60, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Progressive Muscular Atrophy", DC = "8023", R1 = 30, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Syringomyelia", DC = "8024", R1 = 30, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Myasthenia Gravis", DC = "8025", R1 = 30, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Migraine", DC = "8100", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Convulsive Tic", DC = "8103", R1 = 0, R2 = 10, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Paramyoclonus Multiplex", DC = "8104", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Sydenham's or Huntington's Chorea", DC = "8105", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Athetosis", DC = "8107", R1 = 10, R2 = 30, R3 = 50, R4 = 80, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Narcolepsy", DC = "8108", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 80, R6 = 100, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Fifth (Trigeminal) Cranial Nerve Paralysis", DC = "8205", R1 = 10, R2 = 30, R3 = 50, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Seventh (Facial) Cranial Nerve Paralysis", DC = "8207", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Ninth (Glossopharyngeal) Cranial Nerve Paralysis", DC = "8209", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Tenth (Pneumogastric, Vagus) Cranial Nerve Paralysis", DC = "8210", R1 = 10, R2 = 30, R3 = 50, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Eleventh (Spinary Accessory, External Branch) Cranial Nerve Paralysis", DC = "8211", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Twelfth (Hypoglossal) Cranial Nerve Paralysis", DC = "8212", R1 = 10, R2 = 30, R3 = 50, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Radial Nerve Paralysis - Dominant Arm", DC = "8514-1", R1 = 20, R2 = 30, R3 = 50, R4 = 70, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Radial Nerve Paralysis - Non-dominant Arm", DC = "8514-2", R1 = 20, R2 = 20, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Median Nerve Paralysis - Dominant Arm", DC = "8515-1", R1 = 20, R2 = 30, R3 = 50, R4 = 70, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Median Nerve Paralysis - Non-dominant Arm", DC = "8515-2", R1 = 20, R2 = 20, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Ulnar Nerve Paralysis - Dominant Arm", DC = "8516-1", R1 = 20, R2 = 30, R3 = 50, R4 = 70, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Ulnar Nerve Paralysis - Non-dominant Arm", DC = "8516-2", R1 = 20, R2 = 20, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Musculocutaneous Nerve Paralysis - Dominant Arm", DC = "8517-1", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Musculocutaneous Nerve Paralysis - Non-dominant Arm", DC = "8517-2", R1 = 0, R2 = 10, R3 = 20, R4 = 20, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Circumflex Nerve Paralysis - Dominant Arm", DC = "8518-1", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Circumflex Nerve Paralysis - Non-dominant Arm", DC = "8518-2", R1 = 0, R2 = 10, R3 = 20, R4 = 40, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Long Thoracic Nerve Paralysis - Dominant Arm", DC = "8519-1", R1 = 0, R2 = 10, R3 = 20, R4 = 30, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Long Thoracic Nerve Paralysis - Non-dominant Arm", DC = "8519-2", R1 = 0, R2 = 10, R3 = 20, R4 = 20, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Neurological Conditions And Convulsive Disorders", Name = "Major and Minor Epileptic Seizures", DC = "8911", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 80, R6 = 100, R7 = null, R8 = null },
            new() { Area = "Mental", Name = "Mental Disorders", DC = "10000", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = 70, R6 = 100, R7 = null, R8 = null },
            new() { Area = "Mental", Name = "Eating Disorders (Anorexia and Bullimia)", DC = "9520-9521", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Valvular Heart Disease", DC = "7000", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Endocarditis or Pericarditis", DC = "7001-7002", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Pericardial Adhesions", DC = "7003", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Syphilitic Heart Disease", DC = "7004", R1 = 0, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Arteriosclerotic Heart Disease", DC = "7005", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Myocardial Infarction (Heart Attack)", DC = "7006", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Hypertensive Heart Disease", DC = "7007", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Hyperthyroid Heart Disease", DC = "7008", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Bradycardia", DC = "7009", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Supraventricular Tachycardia", DC = "7010", R1 = 10, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Ventricular Arrhythmias", DC = "7011", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Benign Atrioventricular Block", DC = "7015-A", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Non-Benign Atrioventricular Block", DC = "7015-B", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Heart Valve Replacement", DC = "7016", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Coronary Bypass Surgery", DC = "7017", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Implantable Cardiac Pacemaker", DC = "7018", R1 = 10, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Cardiac Transplantation", DC = "7019", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Hypertensive Vascular Disease", DC = "7101", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Aortic Aneurysm", DC = "7110", R1 = 0, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Large Artery Aneurysm", DC = "7111", R1 = 20, R2 = 40, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Small Artery Aneurysm", DC = "7112", R1 = 0, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Arteriovenous Fistula, Traumatic - Arms", DC = "7113-A", R1 = 20, R2 = 40, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Arteriovenous Fistula, Traumatic - Legs", DC = "7113-B", R1 = 30, R2 = 50, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Peripheral Arterial Disease", DC = "7114", R1 = 20, R2 = 40, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Thrombo-angiitis Obliterans (Buerger's Disease)", DC = "7115", R1 = 20, R2 = 40, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Raynaud's Syndrome (Secondary Raynaud's)", DC = "7117", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Angioneurotic Edema", DC = "7118", R1 = 10, R2 = 20, R3 = 40, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Erythromelalgia", DC = "7119", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Varicose Veins", DC = "7120", R1 = 0, R2 = 10, R3 = 20, R4 = 40, R5 = 60, R6 = 100, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Post-Phlebitic Syndrome", DC = "7121", R1 = 0, R2 = 10, R3 = 20, R4 = 40, R5 = 60, R6 = 100, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Cold Injury Residuals", DC = "7122", R1 = 10, R2 = 20, R3 = 30, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Soft Tissue Sarcoma", DC = "7123", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Diseases Of The Heart", Name = "Raynaud's Disease (Primary Raynaud's)", DC = "7124", R1 = 0, R2 = 10, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Deviated Septum", DC = "6502", R1 = 10, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Partial Loss of Nose or Scars", DC = "6504", R1 = 10, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Sinusitis", DC = "6510-6514", R1 = 0, R2 = 10, R3 = 30, R4 = 50, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Tuberculous Laryngitis", DC = "6515", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Chronic Laryngitis", DC = "6516", R1 = 10, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Total Laryngectomy", DC = "6518", R1 = 0, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Aphonia", DC = "6519", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Larynx Stenosis", DC = "6520", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Pharynx Injury", DC = "6521", R1 = 50, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Allergic or Vasomotor Rhinitis", DC = "6522", R1 = 10, R2 = 30, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Bacterial Rhinitis", DC = "6523", R1 = 10, R2 = 50, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Granulomatous Rhinitis", DC = "6524", R1 = 20, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Chronic Bronchitis", DC = "6600", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Bronchiectasis", DC = "6601", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Asthma", DC = "6602", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Pulmonary Emphysema", DC = "6603", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Chronic Obstructive Pulmonary Disease (COPD)", DC = "6604", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Chronic Tuberculosis (Active)", DC = "6701-6704", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Chronic Tuberculosis (inActive)", DC = "6721-6724", R1 = 0, R2 = 20, R3 = 30, R4 = 50, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Pulmonary Vascular Disease", DC = "6817", R1 = 0, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Cancerous Tumor of the Lungs", DC = "6819", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Noncancerous Tumor of the Lungs", DC = "6820", R1 = 0, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Actinomycosis", DC = "6822", R1 = 0, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Nocardiosis", DC = "6823", R1 = 0, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Chronic Lung Abscess", DC = "6824", R1 = 0, R2 = 100, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Diffuse Interstitial Fibrosis", DC = "6825", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Desquamative Interstitial Pneumonitis", DC = "6826", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Pulmonary Alveolar Proteinosis", DC = "6827", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Eosinophilic granuloma of lung", DC = "6828", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Drug-induced pulmonary pneumonitis and fibrosis", DC = "6829", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Radiation-induced pulmonary pneumonitis and fibrosis.", DC = "6830", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Hypersensitivity pneumonitis", DC = "6831", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Pneumoconiosis", DC = "6832", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Asbestosis", DC = "6833", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Histoplasmosis of lung", DC = "6834", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Coccidioidomycosis", DC = "6835", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Blastomycosis", DC = "6836", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Cryptococcosis", DC = "6837", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Aspergillosis", DC = "6838", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Mucormycosis", DC = "6839", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Diaphragm paralysis or paresis", DC = "6840", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Spinal cord injury with respiratory insufficiency", DC = "6841", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Kyphoscoliosis, pectus excavatum, pectus carinatum", DC = "6842", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Traumatic chest wall defect, pneumothorax, hernia", DC = "6843", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Post-surgical residual (lobectomy, pneumonectomy, etc.", DC = "6844", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Chronic pleural effusion or fibrosis", DC = "6845", R1 = 10, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Sarcoidosis", DC = "6846", R1 = 0, R2 = 30, R3 = 60, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Respiratory System", Name = "Sleep Apnea", DC = "6847", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Vibriosis (Cholera, Non-cholera)", DC = "6300", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Visceral leishmaniasis", DC = "6301", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Leprosy (Hansen's disease)", DC = "6302", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Malaria", DC = "6304", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Lymphatic filariasis, to include elephantiasis", DC = "6305", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Bartonellosis", DC = "6306", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Plague", DC = "6307", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Relapsing Fever", DC = "6308", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Rheumatic fever", DC = "6309", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Syphilis, and other treponema infections", DC = "6310", R1 = 0, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Miliary Tuberculosis", DC = "6311", R1 = 0, R2 = 30, R3 = 50, R4 = 100, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Nontuberculosis mycobacterium infection", DC = "6312", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Avitaminosis", DC = "6313", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Beriberi", DC = "6314", R1 = 30, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Pellagra", DC = "6315", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Brucellosis", DC = "6316", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Rickettsial, ehrlichia, and anaplasma infections", DC = "6317", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Melioidosis", DC = "6318", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Lyme Disease", DC = "6319", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Parasitic diseases otherwise not specified", DC = "6320", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Hyperinfection syndrome or disseminated strongyloidiasis", DC = "6325", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Schistosomiasis", DC = "6326", R1 = 0, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Hemorrhagic fevers, including dengue, yellow fever, and others", DC = "6329", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Campylobacter jejuni infection", DC = "6330", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Coxiella burnetii infection (Q fever)", DC = "6331", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Nontyphoid salmonella infections", DC = "6333", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Shigella infections", DC = "6334", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "West Nile virus infection", DC = "6335", R1 = 100, R2 = null, R3 = null, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Lupus erythematosus, systemic", DC = "6350", R1 = 10, R2 = 60, R3 = 100, R4 = null, R5 = null, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "HIV-Related Illness", DC = "6351", R1 = 0, R2 = 10, R3 = 30, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
            new() { Area = "Infectious Diseases, Immune Disorders, And Nutritional Deficiencies", Name = "Chronic Fatigue Syndrome (CFS)", DC = "6354", R1 = 10, R2 = 20, R3 = 40, R4 = 60, R5 = 100, R6 = null, R7 = null, R8 = null },
        };
    }
}