name: Build & Release Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Determine version from installer.iss
      - name: Get Version
        id: get_version
        shell: pwsh
        run: |
          $issPath = "${{ github.workspace }}\installer.iss"
          $content = Get-Content $issPath -Raw
          $match = [regex]::Match($content, '(?m)^\s*AppVersion\s*=\s*(.+)$')
          $version = if ($match.Success) { $match.Groups[1].Value.Trim('"') } else { "1.0.0" }
          Write-Host "Version: $version"
          Add-Content -Path $Env:GITHUB_OUTPUT -Value "version=$version"

      # 4. Publish App
      - name: Publish App
        shell: pwsh
        run: |
          $projectPath = "${{ github.workspace }}\Condition Criteria App.csproj"
          dotnet publish "`"$projectPath`"" -c Release -r win-x64 --self-contained true -o publish\win-x64

      # 5. Prepare installer folder
      - name: Prepare Installer Files
        shell: pwsh
        run: |
          $installerBuild = "${{ github.workspace }}\installer-build"
          New-Item -ItemType Directory -Path $installerBuild -Force | Out-Null
          Copy-Item -Path "${{ github.workspace }}\publish\win-x64\*" -Destination $installerBuild -Recurse -Force
          Copy-Item -Path "${{ github.workspace }}\installer.iss" -Destination $installerBuild -Force

      # 6. Install Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress
        
      - name: Remove old installer EXE
        shell: pwsh
        run: |
          $oldInstaller = "${{ github.workspace }}\installer-build\ConditionCriteriaInstaller.exe"
          if (Test-Path $oldInstaller) { Remove-Item $oldInstaller -Force }

      # 7. Build Installer
      - name: Build Installer
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "/O${{ github.workspace }}\installer-build" "${{ github.workspace }}\installer.iss"
          dir "${{ github.workspace }}\installer-build"

      # 8. Upload Installer Artifact
      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: installer-build\ConditionCriteriaInstaller.exe

      # 9. Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: v${{ steps.get_version.outputs.version }}
          body: "Automated release for version ${{ steps.get_version.outputs.version }}"

      # 10. Upload Installer to Release
      - name: Upload Installer Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: installer-build\ConditionCriteriaInstaller.exe
          asset_name: ConditionCriteriaInstaller.exe
          asset_content_type: application/octet-stream